version: '3'
services:
  api: 
    build: ./api
    ports:
      - "80:80"
    volumes:
      - ./api/:/var/www/html
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
    links:
      - db:db
  db:
    image: mysql
    volumes:
            - "./.data/db:/var/lib/mysql"
    environment:
            MYSQL_ROOT_PASSWORD: ROOT
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      ports:
          - "8080:80"
  front:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
